# Generated by Django 6.0.5 on 2026-06-12 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('icon', models.CharField(default='notifications-outline', max_length=80)),
                ('tone', models.CharField(choices=[('blue', 'Blue'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='blue', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
