# Generated by Django 6.0.5 on 2026-06-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_providerprofile_badge_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='badge_verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('eligible', 'Eligible To Buy'), ('verified', 'Verified')], default='not_verified', max_length=20),
        ),
    ]
