# Generated by Django 6.0.5 on 2026-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_providerprofile_badge_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='city_area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
