# Generated by Django 6.0.5 on 2026-06-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_pin_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin_required_for_access',
            field=models.BooleanField(default=False),
        ),
    ]
