# Generated by Django 6.0.4 on 2026-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dss', '0002_providerscore_batch_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerscore',
            name='batch_eligible_override',
            field=models.BooleanField(default=False, help_text='Admin manually approved this provider for batch KYC verification.'),
        ),
    ]
