# Generated by Django 6.0.4 on 2026-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dss', '0003_providerscore_batch_eligible_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerscore',
            name='badge_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
