# Generated by Django 6.0.4 on 2026-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dss', '0004_providerscore_badge_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchverification',
            name='provider_queue',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
