# Generated by Django 6.0.5 on 2026-06-24 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dss', '0005_batchverification_provider_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerscore',
            name='batch_eligible_override',
            field=models.BooleanField(default=False, help_text='Admin manually approved this provider for trust badge purchase eligibility.'),
        ),
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('integrity_review', 'Integrity Review'), ('score_recalculation', 'Score Recalculation')], max_length=30)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
