# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('escrowed', 'Escrowed'), ('released', 'Released'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
